server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: ${TBOT3_URL}
    username: ${TBOT3_DB_USERNAME}
    password: ${TBOT3_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    open-in-view: false
  jackson:
    serialization:
      indent-output: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
logging:
  level:
    org:
      hibernate: INFO
# Constants
telegram:
  bot:
    username: ${TBOT3_USERNAME}
    token: ${TBOT3_TOKEN}
